### ISSUE TITLE
Upgrade to rails 4.2

### ISSUE THREAD

**Issue by vosechu** [newrelic/newrelic-ruby-kata#14]
I'm willing to do this, but I wanted to ask first if there's any reason not to.

**Comment by tkrajcar** [comment]
None come to mind - I say go for it. Thank you!

**Comment by jasonrclark** [comment]
That would be awesome! :sparkles: 

I popped Rails 4.x in briefly once, and as I recall why I didn't roll with it was that at least one of the samples actually wasn't slow anymore in the base case. So that'd be my only recommendation about it--will see if I made any notes on what was too fast at the time and get back on this issue with it.

Thanks @vosechu!

**Comment by jasonrclark** [comment]
My notes say https://github.com/newrelic/newrelic-ruby-kata/blob/master/app/controllers/big_list_controller.rb no longer exhibited a perf issue once moved to Rails 4.x... Odd to be trying to make slow code, but there you go :smirk:

**Comment by vosechu** [comment]
Thanks @jasonrclark. I'll take a wing at it shortly. @elauervose is doing some work on this so it's fun to do something along side of her!

**Comment by vosechu** [comment]
@jasonrclark @tkrajcar Let me know what you think about the PR. I was able to finish it last night and I hope that it'll help new people get into it. 

The bootstrap changes alone would be a huge hangup for new people. :)

**Comment by jasonrclark** [comment]
Changes look good to me on a first reading. I'm going to sit down and actually test through them side-by-side with the old version to make sure everything still behaves. If there's anything small, I'll probably just fix it, and will let you know how it's going. Thanks again for tackling this!

**Comment by vosechu** [comment]
That would be awesome Jason. Let me know if there's big things that need whacking. :)
